pipeline {
    agent {label 'terraform-label'}
     tools {
        terraform "terraform"
    }
    stages {
        stage('clone-repo') {
            steps {
                checkout scm
            }
        }
        stage('init') {
            steps {
                dir('ddbstatelock/ddb') {
                  sh "terraform init"
                }
            }
        }
        stage('plan') {
            steps {
                dir('ddbstatelock/ddb') {
                  sh "terraform plan -out tf.plan"
                }
            }
        }
        stage('apply') {
            steps {
                dir('ddbstatelock/ddb') {
                  sh "terraform apply tf.plan"
                }
            }
        }
    }
}
